#!/usr/bin/python
# -*- coding: utf-8 -*-

#Top-level function. Specify the corpus, language, and order for all of the analyses

analysisName = "may8_tokenWeighted"
inputDir = "/shared_hd0/corpora/" 
fastStorageDir = "/shared_ssd/ss/"
slowStorageDir = "/shared_hd1/ss/" 

import os, subprocess, re, sys, itertools, codecs, gzip, glob, unicodedata, click, pandas, srilm, pdb, json, multiprocessing, time, tempfile, math, scipy, warnings
#os.chdir('/home/stephan/python/ngrok') #necessary if running from the REPL
import ngrok
#reload(ngrok)


print('Checking for dependencies...')
dependencies = ['ngram','ngram-count','zs','gzrecover']
[ngrok.checkForBinary(d) for d in dependencies]

corporaToAnalyze = [
{'corpus':'GoogleBooks2012',
	'language':'eng-all',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,		
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/eng-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist':'/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/eng-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'GoogleBooks2012',
	'language':'spa-all',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/spa-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/spa-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'es',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'GoogleBooks2012',
	'language':'fre-all',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/fre-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/fre-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'fr',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'GoogleBooks2012',
	'language':'ger-all',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/ger-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/ger-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'inDictionary',
	'country_code': 'de',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'GoogleBooks2012',
	'language':'rus-all', 
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/rus-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/rus-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ru',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'GoogleBooks2012',
	'language':'heb-all',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/heb-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/heb-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'he',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},	
{'corpus':'GoogleBooks2012',
	'language':'ita-all',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/ita-all/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/GoogleBooks2012/ita-all/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'it',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},	
{'corpus':'Google1T',
 	'language':'ENGLISH',
 	'order':'3',
 	'target':'3',
 	'analysisname': analysisName,
 	'inputdir':inputDir,
 	'faststoragedir': fastStorageDir,
 	'slowstoragedir': slowStorageDir,
 	'filterlist':None,
 	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/ENGLISH/00_lexicalSurprisal/unigram_list.txt',
 	'retrievalcount':50000,
 	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/ENGLISH/00_lexicalSurprisal/unigram_list.txt',
 	'modelcount':25000,
 	'dictionary_filter': 'lowerInDictionary',
 	'country_code': 'en',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'SPANISH',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/SPANISH/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/SPANISH/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'es',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'FRENCH',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/FRENCH/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/FRENCH/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'fr',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'DUTCH',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/DUTCH/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/DUTCH/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'nl',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'CZECH',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/CZECH/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/CZECH/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'cs',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'ROMANIAN',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/ROMANIAN/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/ROMANIAN/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ro',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'POLISH',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/POLISH/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/POLISH/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pl',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'PORTUGUESE',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/PORTUGUESE/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/PORTUGUESE/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pt-BR',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'ITALIAN',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/ITALIAN/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/ITALIAN/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'it',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
 {'corpus':'Google1T',
 	'language':'SWEDISH',
 	'order':'3',
	'target':'3',
 	'analysisname': analysisName,
 	'inputdir':inputDir,
 	'faststoragedir': fastStorageDir,
 	'slowstoragedir': slowStorageDir,
 	'filterlist':None,
 	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/SWEDISH/00_lexicalSurprisal/unigram_list.txt',
 	'retrievalcount':50000,
 	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/SWEDISH/00_lexicalSurprisal/unigram_list.txt',
 	'modelcount':25000,
 	'dictionary_filter': 'lowerInDictionary',
 	'country_code': 'sv',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'Google1T',
	'language':'GERMAN',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/Google1T/GERMAN/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/Google1T/GERMAN/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'inDictionary',
	'country_code': 'de',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},		
  {'corpus': 'BNC',
	'language':'eng',
	'order':'3',
 	'target':'3',
	'inputdir':inputDir,
	'filename': 'BNC_merged.txt',
	'analysisname': analysisName,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/BNC/eng/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/BNC/eng/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus': 'BNC',
	'language':'eng-half',
	'order':'3',
 	'target':'3',
	'inputdir':inputDir,
	'filename': 'BNC_merged_half.txt',
	'analysisname': analysisName,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist':None,
	'retrievallist': '/shared_ssd/ss/'+analysisName+'/BNC/eng-half/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/BNC/eng-half/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en',
	'sublex_measures':['ipa','ortho','character'],
	'smoothing':'kn'},
{'corpus':'OPUS',
	'language':'en',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,		
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/en/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist':'/shared_ssd/ss/'+analysisName+'/OPUS/en/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'en',
	'filename':'OPUS_en.txt',	
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/en_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/en_2013_collapsed.txt'
	},
{'corpus':'OPUS',
	'language':'es',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/es/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/es/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'es',
	'filename':'OPUS_es.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/es_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/es_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'fr',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/fr/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/fr/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'fr',
	'filename':'OPUS_fr.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/fr_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/fr_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'de',
	'order':'3',
 	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/de/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/de/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'inDictionary',
	'country_code': 'de',
	'filename':'OPUS_de.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/de_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/de_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'ru', 
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/ru/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/ru/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ru',
	'filename':'OPUS_ru.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/ru_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/ru_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'he',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/he/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/he/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'he',
	'filename':'OPUS_he.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/he_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/he_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'cs',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/cs/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/cs/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'cs',
	'filename':'OPUS_cs.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/cs_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/cs_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'pl',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/pl/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/pl/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pl',
	'filename':'OPUS_pl.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/pl_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/pl_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'ro',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/ro/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/ro/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'ro',
	'filename':'OPUS_ro.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/ro_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/ro_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'sv',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/sv/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/sv/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'sv',
	'filename':'OPUS_sv.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/sv_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/sv_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'nl',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/nl/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/nl/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'nl',
	'filename':'OPUS_nl.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/nl_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/nl_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'pt',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/pt/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/pt/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'pt',
	'filename':'OPUS_pt.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/pt_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/pt_2013_collapsed.txt'},
{'corpus':'OPUS',
	'language':'it',
	'order':'3',
	'target':'3',
	'analysisname': analysisName,
	'inputdir':inputDir,
	'faststoragedir': fastStorageDir,
	'slowstoragedir': slowStorageDir,
	'filterlist': None,
	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/it/00_lexicalSurprisal/unigram_list.txt',
	'retrievalcount':50000,
	'modellist': '/shared_ssd/ss/'+analysisName+'/OPUS/it/00_lexicalSurprisal/unigram_list.txt',
	'modelcount':25000,
	'dictionary_filter': 'lowerInDictionary',
	'country_code': 'it',
	'filename':'OPUS_it.txt',
	'sublex_measures':['ipa','ortho','character','token_ipa','token_character'],
	'smoothing':'kn',
	'token_corpus': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/it_combined.txt',
	'token_filter': '/shared_hd0/corpora/OPUS/2013_OPUS/intermediatecount/it_2013_collapsed.txt'},
# {'corpus':'OPUS',
# 	'language':'en-permuted',
# 	'order':'3',
#  	'target':'3',
# 	'analysisname': analysisName,
# 	'inputdir':inputDir,
# 	'faststoragedir': fastStorageDir,
# 	'slowstoragedir': slowStorageDir,		
# 	'filterlist': None,
# 	'retrievallist':'/shared_ssd/ss/'+analysisName+'/OPUS/en-permuted/00_lexicalSurprisal/unigram_list.txt',
# 	'retrievalcount':50000,
# 	'modellist':'/shared_ssd/ss/'+analysisName+'/OPUS/en-permuted/00_lexicalSurprisal/unigram_list.txt',
# 	'modelcount':25000,
# 	'dictionary_filter': None,
# 	'country_code': 'en',
# 	'filename':'OPUS_en.txt',
#	'sublex_measures':['ipa','ortho','character']},
]

if __name__ == '__main__':
    [ngrok.downloadCorpus(x) for x in corporaToAnalyze]	    
    [ngrok.validateCorpus(x) for x in corporaToAnalyze]    
    [ngrok.analyzeCorpus(x) for x in corporaToAnalyze]
